app/urls.py
from django.conf.urls import url
from . import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^livros/todos/(?P<num>[0-9]+)/$', views.listaTodosLivros, name='listaTodosLivros'),
    url(r'^autores/todos/(?P<num>[0-9]+)/$', views.listaTodosAutores, name='listaTodosAutores'),
    url(r'^livros/(?P<titulo>\w([A-Za-z-])+)/$', views.detalhes, name='detalhes'),
    url(r'^cadastro/livro$', views.methLivro, name='methLivro'),
    url(r'^cadastro/autor$', views.methAutor, name='methAutor'),
    #url(r'^teste/(?P<pk>[0-9]+)/$', views.teste, name='teste'),
]

livros/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
import PIL 
from PIL import Image
from stdimage import StdImageField

class Autor(models.Model):
    nome = models.CharField('Autor', max_length=50)
    anoNasc = models.PositiveSmallIntegerField()
    def __str__(self):
        return self.nome

class Editora(models.Model):
    nome = models.CharField('Editora', max_length=50)

    def __str__(self):
        return self.nome

class Livro(models.Model):
    titulo = models.CharField(max_length=50)
    ano = models.PositiveSmallIntegerField()
    descricao = models.CharField(max_length=1500)
    capa = StdImageField(upload_to='capas', variations={'normal': (370, 530, True), 'thumbnail': (170, 230, True), 'minithumb': (100, 160)})
    
    def ChamarUrl(self):
        aux = self.titulo
        return aux.replace(' ', '-')

    def Resumo(self):
        if len(self.descricao) > 300:
            aux = ''
            for c in range(300):
                aux += self.descricao[c]
            return aux + '...'
        else:
            return self.descricao

    def __str__(self):
        return self.titulo

class AutorLivro(models.Model):
    autor = models.ForeignKey(Autor)
    livro = models.ForeignKey(Livro)

class EditoraLivro(models.Model):
    editora = models.ForeignKey(Editora)
    livro = models.ForeignKey(Livro)

app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Livro, Autor, AutorLivro

def index(request):
    aux = Livro.objects.all()
    livros = []
    if len(aux) <= 6:
        livros = aux
    else:
        for i in range(6):
            livros.append(aux[i])

    context = {'livros': livros, 'pag': 'index'}
    template = loader.get_template('app/header.html')
    return HttpResponse(template.render(context, request))

def detalhes(request, titulo):
    if '-' in titulo:
        titulo = titulo.replace('-', ' ')

    livro = Livro.objects.get(titulo=titulo)
    try:
        autor = AutorLivro.objects.get(livro=livro)
    except:
        autor = None
    
    context = {'livro': livro, 'autor': autor, 'pag': 'detalhes'}
    template = loader.get_template('app/header.html')
    return HttpResponse(template.render(context, request))
    
def methAutor(request):
    if request.method == 'POST':
        op = request.POST['frmOp']
        if op == 'cadastrar':
            Pnome = request.POST['txtNome']
            Pano = request.POST['txtAno']

            autor = Autor(nome=Pnome, anoNasc=Pano)
            autor.save()

    context = {'pag': 'cadastroAutor'}
    template = loader.get_template('app/header.html')
    return HttpResponse(template.render(context, request))

def methLivro(request):
    if request.method == 'POST':
        op = request.POST['frmOp']
        if op == 'cadastrar':
            Ptitulo = request.POST['txtTitulo']; Ptitulo = Ptitulo.replace('-', ' ').replace(':', '')
            Pano = request.POST['txtAno'] + '-01-01'
            Pdescricao = request.POST['txtDescricao']
            Pcapa = request.POST['imgCapa']
            Pautor = request.POST['cbxAutor']
            Pautor = Autor.objects.get(nome=Pautor)
            
            livro = Livro(titulo=Ptitulo, ano=Pano, descricao=Pdescricao, capa=Pcapa)
            livro.save()

            AutorLivro(autor=Pautor, livro=livro).save()

    autores = Autor.objects.all()
    context = {'pag': 'cadastroLivro', 'autores': autores}
    template = loader.get_template('app/header.html')
    return HttpResponse(template.render(context, request))

def listaTodosLivros(request, num=1):
    livros = Livro.objects.all()

    pagination = []
    if len(livros) > 5:
        aux = []
        for i in range(len(livros)):
            if len(aux) == 5:
                pagination.append(aux)
                aux = []
            else:
                aux.append(livros[i])
        pagination.append(aux)

        dic = {}
        for i in reversed(range(len(pagination))):
            dic[str(i+1)] = pagination[i]

        total = list(range(1, len(dic)+1))
        livros = dic[num]
    else:
        total = [1]

    context = {'livros': livros, 'pag': 'todosLivros', 'ultimo': total[-1], 'atual': int(num), 'total': total, 'prox': int(num)+1, 'ant': int(num)-1}
    template = loader.get_template('app/header.html')
    return HttpResponse(template.render(context, request))

def listaTodosAutores(request, num=1):
    autores = Autor.objects.all()
    autLivr = AutorLivro.objects.all()

    pagination = []
    if len(autores) > 10:
        aux = []
        for i in range(len(autores)):
            if len(aux) == 10:
                pagination.append(aux)
                aux = []
            else:
                aux.append(autores[i])
        pagination.append(aux)

        dic = {}
        for i in reversed(range(len(pagination))):
            dic[str(i+1)] = pagination[i]

        total = list(range(1, len(dic)+1))
        autores = dic[num]
    else:
        total = [1]

    quant = {}
    for autor in autores:
        aux = 0
        for item in autLivr:
            if item.autor == autor:
                aux += 1
        quant[autor] = aux

    context = {'autores': autores, 'quant': quant, 'pag': 'todosAutores', 'ultimo': total[-1], 'atual': int(num), 'total': total, 'prox': int(num)+1, 'ant': int(num)-1}
    template = loader.get_template('app/header.html')
    return HttpResponse(template.render(context, request))

app/templates/app/cadastroAutor.html
<body>
    <div class="div-centro">
        <div class="well form-group">
            <h2>Autor</h2>
            <form action="{% url 'app:methAutor' %}" method="POST">{% csrf_token %}
                <label for="nome">Nome:</label>
                <input type="text" class="form-control" id="nome" name="txtNome" />

                <label for="ano">Ano Nascimento:</label>
                <input type="number" class="form-control" id="ano" name="txtAno" />
                <br>
            
                <input type="submit" class="form-control btn-primary" value="CADASTRAR" />
                <input type="hidden" value="cadastrar" name="frmOp" />
            </form>
        </div>
    </div>
</body>

app/templates/app/cadastroLivro.html
<body>
    <div class="div-centro">
        <div class="well form-group">
            <h2>Livro</h2>
            <form action="{% url 'app:methLivro' %}" method="POST">{% csrf_token %}
                <label for="titulo">Titulo:</label>
                <input type="text" class="form-control" id="titulo" name="txtTitulo" />

                <label for="ano">Ano:</label>
                <input type="number" class="form-control" id="ano" name="txtAno" />

                <label for="descricao">Descrição:</label>
                <textarea rows="4" cols="50" class="form-control" id="descricao" name="txtDescricao" ></textarea>

                <label for="capa">Capa:</label>
                <input type="file" class="form-control" id="capa" name="imgCapa" />

                <label for="autor">Autores:</label>
                <select class="form-control" id="autor" name="cbxAutor" >
                    {% for aut in autores %}
                        <option value="{{aut}}">{{aut.nome}}({{aut.anoNasc}})</option>
                    {% endfor %}
                </select>
                <br>

                <input type="submit" class="form-control btn-primary" value="CADASTRAR" />
                <input type="hidden" value="cadastrar" name="frmOp" />
            </form>
        </div>
    </div>
</body>

app/templates/app/detalhes.html
<body>
    <div class="container">
        <div class="jumbotron">
            <h1><i class="col-md-10">{{livro.titulo}}</i></h1>

            <img src="{{livro.capa.minithumb.url}}" alt="{{livro.titulo}}" data-toggle="modal" data-target="#myModal" />

            <h6>{{autor.autor}} - {{livro.ano}}</h6>
            <p>{{livro.descricao}}</p>


            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">{{livro.titulo}}</h4>
                            </div>
                        <div class="modal-body">
                            <img src="{{livro.capa.normal.url}}" alt="{{livro.titulo}}" />
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</body>

app/templates/app/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'app/JavaScript/paginacao.js' %}"></script>

    <title>
        {% if pag == 'index' %}
            Home
        {% elif pag == 'detalhes' %}
            Detalhes - {{livro.titulo}}
        {% elif pag == 'cadastroLivro' %}
            Novo Livro
        {% elif pag == 'cadastroAutor' %}
            Novo Autor
        {% elif pag == 'todos' %}
            Livros
        {% endif %}
    </title>
</head>

<header>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span> 
                </button>
                <a class="navbar-brand" href="{% url 'app:index' %}">BookS</a>
            </div>

            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Cadastro
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                        <li><a href="{% url 'app:methLivro' %}">Livros</a></li>
                        <li><a href="{% url 'app:methAutor' %}">Autores</a></li>
                        <li><a href="#">Editoras</a></li> 
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Lista
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                        <li><a href="{% url 'app:listaTodosLivros' 1 %}">Livros</a></li>
                        <li><a href="{% url 'app:listaTodosAutores' 1 %}">Autores</a></li>
                        <li><a href="#">Editoras</a></li> 
                        </ul>
                    </li>

                    <li><a href="{% url 'app:listaTodosLivros' 1 %}">Lista</a></li> 
                    <li><a href="#">Page 3</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="../admin/">Admin</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>

{% if pag == 'index' %}
    {% include "app/index.html" %}
{% elif pag == 'detalhes' %}
    {% include "app/detalhes.html" %}
{% elif pag == 'cadastroLivro' %}
    {% include "app/cadastroLivro.html" %}
{% elif pag == 'cadastroAutor' %}
    {% include "app/cadastroAutor.html" %}
{% elif pag == 'todosLivros' %}
    {% include "app/listaLivros.html" %}
{% elif pag == 'todosAutores' %}
    {% include "app/listaAutores.html" %}
{% endif %}

app/templates/app/index.html
<body>
    <div class="container div-centro">
        {% if livros %}
            <div class="container">
                {% for livro in livros %}
                    <div class="col-md-4 grid-6">
                        {% if ' ' in livro.titulo %}
                            <a href="{% url 'app:detalhes' livro.ChamarUrl %}">
                        {% else %}
                            <a href="{% url 'app:detalhes' livro.titulo %}">
                        {% endif %}
                        <img id="grid-img" class="grid-6-shadow" src="{{livro.capa.thumbnail.url}}" alt="{{livro.titulo}}"/></a>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</body>

app/templates/app/listaAutores.html
<body>
    <div class="container div-centro">
        {% if autores %}
            <div class="container">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Autor</th>
                            <th>Nº Livros</th>
                        </tr>
                    </thead>
                    <tbody>
                {% for autor in autores %}
                    <tr>
                        <td><a href="#">{{autor.nome}}</a></td>
                        <td>
                            {% for key, item in quant.items %}
                                {% if key == autor %}
                                    {{item}}
                                {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
                    </tbody>
                </table>
            </div>

            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if atual == 1 %}
                        <li class="disabled">
                            <a aria-label="Previous">
                    {% else %}
                        <li>
                            <a href="{% url 'app:listaTodosAutores' ant %}" aria-label="Previous">
                    {% endif %}
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>

                    {% for n in total %}
                        {% if n == atual %}
                            <li class="active">
                                <span>{{n}} <span class="sr-only">(current)</span></span>
                        {% else %}
                            <li>
                            <a href="{% url 'app:listaTodosAutores' n %}" >{{n}} </a>
                        {% endif %}
                        </li>
                    {% endfor %}

                    {% if atual == ultimo %}
                        <li class="disabled">
                            <a aria-label="Next">
                    {% else %}
                        <li>
                            <a href="{% url 'app:listaTodosAutores' prox %}" aria-label="Next">
                    {% endif %}
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        {% endif %}
    </div>
</body>

app/templates/app/listaLivros.html
<body>
    <div class="container div-centro">

        {% if livros %}
            <div class="container-fluid">
                {% for livro in livros %}
                    <div class="row grid-row">
                        <div class="col-md-2">
                            {% if ' ' in livro.titulo %}
                                <a href="{% url 'app:detalhes' livro.ChamarUrl %}">
                            {% else %}
                                <a href="{% url 'app:detalhes' livro.titulo %}">
                            {% endif %}
                                <img id="grid-img" class="grid-6-shadow" src="{{livro.capa.thumbnail.url}}" alt="{{livro.titulo}}" /></a>
                        </div>
                        <div class="col-md-8 texto-centro">
                            {% if ' ' in livro.titulo %}
                                <a href="{% url 'app:detalhes' livro.ChamarUrl %}">
                            {% else %}
                                <a href="{% url 'app:detalhes' livro.titulo %}">
                            {% endif %}
                                <h4>{{livro.Resumo}}</h4></a>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if atual == 1 %}
                        <li class="disabled">
                            <a aria-label="Previous">
                    {% else %}
                        <li>
                            <a href="{% url 'app:listaTodosLivros' ant %}" aria-label="Previous">
                    {% endif %}
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>

                    {% for n in total %}
                        {% if n == atual %}
                            <li class="active">
                                <span>{{n}} <span class="sr-only">(current)</span></span>
                        {% else %}
                            <li>
                            <a href="{% url 'app:listaTodosLivros' n %}" >{{n}} </a>
                        {% endif %}
                        </li>
                    {% endfor %}

                    {% if atual == ultimo %}
                        <li class="disabled">
                            <a aria-label="Next">
                    {% else %}
                        <li>
                            <a href="{% url 'app:listaTodosLivros' prox %}" aria-label="Next">
                    {% endif %}
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        {% endif %}
    </div>
</body>